const { director } = require('./director');
const ep = async d => {
  const { p } = d;
  const card = p.locator('.swipe-fg:visible', { hasText: 'Chiara Galli' }).first();
  await card.scrollIntoViewIfNeeded(); await p.mouse.wheel(0, 120); await d.wait(600);
  await d.shot({ t: '“Sono *celiaca*”', s: 'Detto al telefono, scritto sulla prenotazione', zoom: await d.zoomOn(card, 8) });
  await d.swipe(card, 230, { silent: true });
  await d.tap(d.V('Servizio'), { silent: true, after: 1400 });
  const tile = p.locator('#arrived-list .btn-tap:visible', { hasText: 'Chiara' }).first();
  await d.shot({ b: 6, t: 'Arrivano *al tavolo*', s: 'Tocchi il tavolo 9 in Servizio' });
  await d.tap(tile, { after: 1200 });
  await d.shot({ b: 6, t: 'Prima cosa: *accoglienza*', s: 'Il pulsante Accoglienza' });
  await d.tap(p.locator('#servizio-modal button:visible', { hasText: /accoglienza/i }).first(), { after: 1200 });
  await d.shot({ t: 'Chiedi le *allergie*', s: 'I 14 allergeni di legge, più una voce libera. O “Nessuno”' });
  await d.tap(p.locator('label:visible', { hasText: 'Glutine' }).first(), { after: 500 });
  await d.shot({ b: 6, t: 'Glutine, *segnato*', s: 'Poi Conferma' });
  await d.tap(d.R(/^\s*conferma\s*$/i), { after: 1400 });
  await d.shot({ t: 'Resta *sul tavolo*', s: 'Tutto lo staff vede “Allergeni: Glutine”', zoom: await d.zoomOn(p.locator('#servizio-modal').getByText(/Allergeni:/).first(), 30) });
  await p.evaluate(() => closeServizioModal()); await d.wait(800);
  await d.shot({ b: 6, t: 'Anche *da lontano*', s: 'La spiga sulla tessera del tavolo', zoom: await d.zoomOn(tile, 20) });
  await d.tap(tile, { after: 1200 });
  await d.shot({ b: 6, t: 'Ora la *comanda*', s: 'Tieni premuto Comanda' });
  await d.tap(p.locator('#servizio-modal button:visible', { hasText: /comanda/i }).first(), { press: 900, after: 1500 });
  const m = p.locator('#comanda-modal');
  await d.shot({ b: 6, t: 'Scegli la *categoria*', s: 'Primi' });
  await d.tap(m.getByText(/^\s*primi\s*$/i).first(), { after: 900 });
  await d.shot({ b: 12, t: 'I piatti a rischio sono *in rosso*', s: 'Tagliatelle, spaghetti, gnocchi: contengono glutine. Il risotto no' });
  await d.tap(m.getByText('Categorie').first(), { after: 700 });
  await d.tap(m.getByText(/^\s*dolci\s*$/i).first(), { after: 900 });
  await d.shot({ b: 8, t: 'In *ogni categoria*', s: 'Il tiramisù sì, panna cotta e sorbetto no' });
  await p.evaluate(() => closeComandaComposer()); await d.wait(700); if (await p.locator('#servizio-modal:visible').count()) { await p.evaluate(() => closeServizioModal()); await d.wait(600); }
  await d.menu('Impostazioni'); await d.tap(d.V('Piatti'), { silent: true, after: 1200 });
  await d.tap(d.V('Primi'), { silent: true, after: 1000 });
  await d.tap(p.locator('[onclick^="openEditDishModal("]:visible').first(), { silent: true, after: 1200 });
  const al = p.locator('#dish-form-allergens');
  await d.wait(900); await al.evaluate(e => e.scrollIntoView({ block: 'center' })); await d.wait(700);
  await d.shot({ b: 10, t: 'Lo sai perché *lo scrivi tu*', s: 'Su ogni piatto spunti i suoi allergeni, una volta sola', zoom: await d.zoomOn(al, 10) });
};
ep.pre = async () => { for (const d of (await col('bookings').get()).docs) { const x = d.data(); if (x.name === 'Chiara Galli') await d.ref.update({ arrived: false, arrivedAt: null, welcome: false, allergens: [], welcomeAllergens: [], notes: 'Celiaca' }); } };
director('allergeni', ep);
