const { director } = require('./director');
const ep = async d => {
  const { p } = d;
  const Q = sel => p.locator(sel).locator('visible=true').first();
  await d.menu('Cassa');
  await d.shot({ b: 8, t: 'La *cassa*', s: 'Tutti i tavoli con il conto aperto, già con le loro comande' });
  await d.tap(p.locator('#tab-cassa').getByText('Famiglia Bianchi').first(), { after: 1400 });
  await d.shot({ b: 10, t: 'Il conto è *già pronto*', s: 'Ogni piatto della comanda, con aggiunte e prezzi. Niente da ribattere' });
  await p.mouse.wheel(0, 500); await d.wait(700);
  await d.shot({ b: 8, t: 'Il coperto *si mette da solo*', s: 'Uno a persona, e lo cambi con un tocco', zoom: await d.zoomOn(p.locator('#tab-cassa').getByText(/^\s*Coperto\s*$/).first().locator('xpath=ancestor::div[2]'), 10) });
  await d.tap(Q('[onclick="openDividiContoModal()"]'), { after: 1100 });
  await d.shot({ b: 8, t: 'Dividi *alla romana*', s: 'In parti uguali: quanti sono, e fa il conto a persona' });
  await d.tap(d.R(/^\s*per piatto\s*$/i), { after: 1000 });
  await d.shot({ b: 8, t: 'O *per piatto*', s: 'Ognuno paga quello che ha preso' });
  await p.keyboard.press('Escape'); await p.evaluate(() => { for (const f of ['closeDividiContoModal']) if (typeof window[f] === 'function') window[f](); }); await d.wait(700);
  await d.shot({ b: 6, t: 'Uno *sconto*?', s: 'Apri “Altre azioni”' });
  await d.tap(p.locator('#tab-cassa').getByText('Altre azioni').first(), { after: 900 });
  await p.mouse.wheel(0, 400); await d.wait(600);
  await d.shot({ b: 8, t: 'Altre *azioni*', s: 'Coperti, menù concordato a prezzo fisso, abbuono, scontrino parlante, sospeso' });
  await d.tap(Q('[onclick="openAbbuonoModal()"]'), { after: 1000 });
  await p.locator('[id*=abbuono] input:visible').first().fill('4.50').catch(() => {});
  await p.locator('[id*=abbuono] input:visible').nth(1).fill('Arrotondamento').catch(() => {});
  await d.shot({ b: 8, t: '*Abbuono*', s: 'Arrotondi o togli qualcosa dal totale, con il motivo' });
  await d.tap(Q('[onclick="submitAbbuono()"]'), { after: 1200 });
  await d.shot({ b: 6, t: 'Totale *aggiornato*', s: 'L’abbuono resta scritto nel conto' });
  await p.mouse.wheel(0, -300); await d.wait(500);
  await d.tap(Q('[onclick="toggleContoSaldato()"]'), { after: 1100 });
  await d.shot({ b: 8, t: 'Contanti o *carta*?', s: 'Segna saldato e scegli come hanno pagato' });
  await d.tap(d.R(/carta\s*\/\s*pos/i), { after: 1400 });
  await d.shot({ b: 8, t: '*Saldato*', s: 'Il tavolo resta occupato finché non lo liberi', settle: 300 });
  // sospeso on table 8
  await p.mouse.wheel(0, -2000); await d.wait(500);
  await p.locator('#tab-cassa').getByText('Tavoli', { exact: true }).locator('visible=true').first().click(); await d.wait(1000);
  await p.locator('#tab-cassa').getByText('Giulia Verdi').locator('visible=true').first().click(); await d.wait(1300);
  await d.tap(p.locator('#tab-cassa').getByText('Altre azioni').first(), { silent: true, after: 900 });
  await p.mouse.wheel(0, 500); await d.wait(600);
  await d.shot({ b: 6, t: 'Pagano *domani*?', s: 'Giulia è una cliente fissa: “Metti in sospeso”' });
  await d.tap(Q('[onclick="openMettiSospesoModal()"]'), { after: 1000 });
  const si = p.locator('[id^="metti-sospeso"] input:visible, [id^="metti-sospeso"] textarea:visible');
  await si.first().fill('Giulia Verdi'); if (await si.count() > 1) await si.nth(1).fill('Passa a pagare venerdì').catch(() => {}); await d.wait(400);
  await d.shot({ b: 8, t: 'Conto *in sospeso*', s: 'A nome di chi, e lo ritrovi quando passa a pagare' });
  await d.tap(Q('[onclick="submitMettiSospeso()"]'), { after: 1400 });
  await p.mouse.wheel(0, -2000); await d.wait(500);
  await p.evaluate(() => { const m = document.querySelector('[id^="metti-sospeso"][id$="modal"]'); if (typeof closeCassaTable === 'function') closeCassaTable(); }); await d.wait(1000);
  await d.tap(Q('[onclick="openSospesiList()"]'), { after: 1100 });
  await d.shot({ b: 8, t: 'I *sospesi*', s: 'Tutti in un elenco, da saldare in contanti o carta quando tornano' });
  await p.evaluate(() => closeSospesiList()); await d.wait(600);
  await d.tap(Q('[onclick="openRiepilogoSerata()"]'), { after: 1300 });
  await d.shot({ b: 10, t: 'Il *riepilogo* della serata', s: 'Incassato, contanti e carta, sospesi: la chiusura in una schermata' });
};
ep.pre = async () => {
  const items = {}, cats = {}; for (const d of (await col('menuCategories').get()).docs) cats[d.id] = d.data().destinationId || null; for (const d of (await col('menuItems').get()).docs) items[d.data().name] = { id: d.id, ...d.data() };
  const L = (n, qty, uscita) => ({ menuItemId: items[n].id, name: n, price: items[n].price, qty, uscita, extras: [], removals: [], destinationId: items[n].destinationOverrideId || cats[items[n].categoryId] });
  for (const d of (await col('bookings').get()).docs) { const x = d.data();
    if (['Famiglia Bianchi', 'Giulia Verdi'].includes(x.name)) await d.ref.update({ contoSaldato: false, contoSaldatoAt: null, metodoPagamento: null, contoSaldatoImporto: null, abbuono: null, menuConcordato: null });
    if (x.name === 'Giulia Verdi') await col('comande').doc(d.id).set({ bookingId: d.id, updatedAt: firebase.firestore.FieldValue.serverTimestamp(), items: [L('Bruschette al pomodoro', 2, 1), L('Risotto ai porcini', 3, 2), L('Gnocchi al pomodoro', 3, 2), L('Tiramisù', 4, 3), L('Vino della casa ¼', 3, 1), L('Acqua frizzante', 2, 1)] });
  }
  for (const d of (await col('sospesi').get()).docs) await d.ref.delete();
};
director('cassa', ep);
