const { director } = require('./director');
const ep = async d => {
  const { p } = d; const Q = sel => p.locator(sel).locator('visible=true').first();
  await d.tap(p.locator('[aria-label="Apri menu"]'), { silent: true, after: 700 });
  await d.tap(d.V('Impostazioni'), { silent: true, after: 1300 });
  await d.V('Piatti').evaluate(e => e.scrollIntoView({ block: 'center' })); await d.wait(600);
  await d.shot({ b: 6, t: 'Il menu *è nell’app*', s: 'Impostazioni › Piatti' });
  await d.tap(d.V('Piatti'), { after: 1300 });
  await d.shot({ t: 'Categorie e *piatti*', s: 'Con il coperto automatico, le aggiunte standard e l’import' });
  await d.tap(d.V('Primi'), { after: 1100 });
  await d.shot({ b: 6, t: 'Ogni categoria ha la sua *uscita*', s: 'I primi vanno in Cucina' });
  await d.tap(p.locator('[onclick^="openEditDishModal("]:visible').first(), { after: 1300 });
  await d.shot({ b: 6, t: 'La scheda del *piatto*', s: 'Nome, prezzo, descrizione' });
  const al = p.locator('#dish-form-allergens'); await al.evaluate(e => e.scrollIntoView({ block: 'center' })); await d.wait(700);
  await d.shot({ b: 10, t: 'Allergeni e *asporto*', s: 'Spunti gli allergeni una volta, e scegli se il piatto si ordina da asporto', zoom: await d.zoomUnion(al, p.locator('#dish-form-asporto'), 12) });
  await p.evaluate(() => closeDishModal()); await d.wait(700);
  await d.tap(d.V('Nuova categoria'), { after: 1100 });
  await d.shot({ b: 8, t: 'Cucina, bar, *pizzeria*…', s: 'Decidi dove arriva la comanda di ogni categoria' });
  await d.tap(p.locator('[id^="category"] :text-is("Gestisci"):visible, :text-is("Gestisci"):visible').first(), { after: 1100 });
  await d.shot({ b: 8, t: 'Le *destinazioni*', s: 'Una per postazione: la cucina vede i piatti, il bar le bevande' });
  await p.evaluate(() => { closeDestinationsModal(); }); await d.wait(500);
  await p.evaluate(() => { if (typeof closeCategoryModal === 'function') closeCategoryModal(); }); await p.keyboard.press('Escape'); await d.wait(700);
  await d.tap(Q('[onclick="openMenuImportModal()"]'), { silent: true, after: 1200 });
  await p.locator('#menu-import-text').fill('## Pizze | Cucina\nMargherita - 7.00 - Pomodoro, mozzarella, basilico\nDiavola - 8.50 - Salame piccante\nCapricciosa - 9.00\n\n## Birre | Bar\nBionda alla spina 0,4 - 5.00\nRossa artigianale - 6.00\n\n## Dolci | Cucina\nCannolo - 4.00\nCaffè - 1.50 | Bar');
  await p.locator('#menu-import-text').evaluate(e => e.scrollTop = 0); await d.wait(400);
  await d.shot({ b: 10, t: 'Hai già il menu? *Importalo*', s: 'Carichi il PDF o una foto: l’intelligenza artificiale lo trascrive, tu controlli e importi' });
  await p.evaluate(() => closeMenuImportModal()); await d.wait(700);
  await d.tap(Q('[onclick="openCopertoSettingModal()"]'), { silent: true, after: 1100 });
  await d.shot({ b: 8, t: 'Il *coperto*', s: 'Scegli la voce, e in cassa si aggiunge da solo, uno a persona' });
  await p.evaluate(() => { if (typeof closeCopertoSettingModal === 'function') closeCopertoSettingModal(); }); await p.keyboard.press('Escape'); await d.wait(600);
  await p.evaluate(() => switchTab('impostazioni')); await d.wait(1000);
  const st = d.V('Stampante comande'); await st.evaluate(e => e.scrollIntoView({ block: 'center' })); await d.wait(500);
  await d.tap(st, { silent: true, after: 900 });
  await st.evaluate(e => e.scrollIntoView({ block: 'start' })); await p.mouse.wheel(0, -80); await d.wait(600);
  await d.shot({ b: 10, t: 'Stampa in *cucina*', s: 'Stampante comande di rete: basta l’indirizzo IP. Stampa comande e preconto, non scontrini fiscali' });
};
director('menu', ep);
