const { director } = require('./director');
const ep = async d => {
  const { p } = d;
  await d.tap(p.locator('[aria-label="Apri menu"]'), { silent: true, after: 700 });
  await d.tap(d.V('Richieste prenotazione'), { silent: true, after: 1400 });
  const link = await p.evaluate(() => [...document.querySelectorAll('input,a,code,span,div,p')].map(e => (e.value || e.textContent || '').trim()).find(t => /^https:\/\/\S*prenota\.html\?r=\S+$/.test(t)));
  await d.shot({ t: 'Il *link* del tuo locale', s: 'Lo metti su Instagram, Google, WhatsApp, sul sito', zoom: await d.zoomOn(p.getByText('Il tuo link pubblico', { exact: false }).first().locator('xpath=ancestor::div[2]'), 8) });
  await d.tap(d.R(/^\s*copia\s*$/i), { after: 1000 });
  await d.shot({ b: 6, t: 'Copiato', s: 'E chi prenota non ti chiama più', settle: 200 });
  await p.goto(link, { waitUntil: 'load' }); await d.wait(2500);
  await d.shot({ b: 8, t: 'Il cliente apre *il link*', s: 'Una pagina col nome del tuo locale, dal telefono' });
  await p.locator('input:visible').nth(0).fill('Sofia Rinaldi');
  await p.locator('input[type=tel]:visible, input[placeholder*="ricontatt"]:visible').first().fill('347 000 0000');
  const sel = p.locator('select:visible').first(); await sel.selectOption('21:00');
  await p.locator('button:visible', { hasText: /^\s*\+\s*$/ }).first().click(); await d.wait(200);
  await p.locator('textarea:visible').first().fill('Se possibile un tavolo tranquillo');
  await p.mouse.wheel(0, 300); await d.wait(600);
  await d.shot({ b: 8, t: 'Compila in *pochi secondi*', s: 'Nome, telefono o email, giorno, ora, persone, note' });
  await d.tap(p.getByText(/invia richiesta/i).locator('visible=true').first(), { after: 2500 });
  await d.shot({ b: 8, t: 'Richiesta *inviata*', s: 'Il cliente sa che il locale confermerà a breve', settle: 300 });
  await p.goto('https://salaflow-6d0f7.web.app/', { waitUntil: 'load' }); await d.wait(4000);
  await p.locator('[aria-label="Apri menu"]').click(); await d.wait(700); await d.V('Richieste prenotazione').click(); await d.wait(1600);
  const card = p.getByText('Sofia Rinaldi').locator('visible=true').first(); await card.evaluate(e => e.scrollIntoView({ block: 'center' })); await d.wait(600);
  await d.shot({ b: 8, t: 'Arriva *in app*', s: 'Con una notifica a tutto lo staff. Tu accetti o rifiuti' });
  await d.tap(d.R(/accetta/i), { after: 1500 });
  await d.shot({ b: 10, t: 'Accetti: *è già compilata*', s: 'Nome, ora, persone, note. E il tavolo lo suggerisce SalaFlow' });
  await d.tap(d.R(/salva prenotazione/i), { after: 1500 });
  await d.shot({ b: 8, t: 'Prenotazione *confermata*', s: 'È in lista e sulla piantina. Se ha lasciato l’email, riceve la conferma', settle: 300 });
};
ep.pre = async () => { for (const c of ['bookingRequests']) for (const d of (await col(c).get()).docs) await d.ref.delete(); for (const d of (await col('bookings').get()).docs) if (d.data().name === 'Sofia Rinaldi') await d.ref.delete(); };
director('online', ep);
