const { director } = require('./director');
const ep = async d => {
  const { p } = d;
  await d.shot({ t: 'La serata in *quattro numeri*', s: 'Coperti, arrivati, prenotati, in arrivo: aggiornati da soli', zoom: await d.zoomOn(p.locator('#stat-pending-tables').locator('xpath=ancestor::div[contains(@class,"rounded-3xl") or contains(@class,"rounded-2xl")][1]'), 6) });
  await d.tap(p.locator('[onclick="showStatModal(\'pending\')"]'), { after: 1200 });
  await d.shot({ b: 8, t: 'Chi deve *ancora arrivare*?', s: 'Tocchi una casella e hai l’elenco, con orario e persone' });
  await p.evaluate(() => typeof closeStatModal === 'function' ? closeStatModal() : null); await p.keyboard.press('Escape'); await d.wait(600);
  const x = p.locator('[onclick*="closeStatModal"]:visible').first(); if (await x.count()) await x.click(); await d.wait(600);
  await d.shot({ b: 6, t: 'Filtra la *lista*', s: 'Tutti, non arrivati, arrivati, per sala o per orario' });
  await d.tap(d.V('Non Arrivati'), { after: 900 });
  await d.shot({ t: 'Solo chi *manca*', s: 'Il ritardatario salta all’occhio' });
  await d.tap(d.V('Tutti'), { silent: true, after: 700 });
  await d.tap(d.V('Non Arrivati'), { silent: true, after: 700 });
  const card = p.locator('.swipe-fg:visible', { hasText: 'Luca Moretti' }).first();
  await d.shot({ t: 'Arrivano? *Trascini* a destra', s: 'Luca Moretti, 4 persone, tavolo 3' });
  await d.swipe(card, 230, { mid: { b: 4, t: 'Arrivano? *Trascini* a destra', s: 'Sotto compare “Arrivato”: lasci e fatto' } });
  await d.shot({ t: 'Segnati come *arrivati*', s: 'Parte il timer: sai da quanto sono seduti', settle: 200 });
  await d.tap(d.V('Tutti'), { silent: true, after: 900 });
  const ef = p.locator('.swipe-fg:visible', { hasText: 'Elena Ferrari' }).first();
  await ef.scrollIntoViewIfNeeded(); await d.wait(500);
  await d.shot({ t: 'Non si presentano?', s: 'Il tasto *no show* libera il tavolo' });
  await d.tap(ef.locator('[title*="No Show" i], [aria-label*="No Show" i], button:has-text("⊘")').first().or(ef.locator('button').nth(-2)), { after: 1200 });
  await d.shot({ b: 8, t: 'Segnato *no show*', s: 'Resta nello storico, e il tavolo torna libero per altri' });
  const gv = p.locator('.swipe-fg:visible', { hasText: 'Giulia Verdi' }).first();
  await gv.scrollIntoViewIfNeeded(); await d.wait(500);
  await d.shot({ t: 'Cambia *qualcosa*?', s: 'Arrivano in 7 invece di 6: matita e modifichi' });
  await d.tap(gv.locator('button').last(), { after: 1200 });
  await d.shot({ b: 8, t: 'Modifica al volo', s: 'Persone, tavolo, orario, note: tutto modificabile' });
  await d.tap(p.locator('#edit-booking-form [aria-label="Aumenta persone"]:visible, #edit-booking-form button:visible:has-text("+")').first(), { after: 700 });
  await d.shot({ b: 6, t: 'Ora sono *7*', s: 'Salvi e lo vede tutto lo staff' });
  await d.tap(p.locator('#edit-booking-form button[type=submit]:visible').first(), { after: 1400 });
  await d.shot({ t: 'Cerca chiunque', s: 'Nome o numero di tavolo, anche serate passate o future' });
  await d.tap(d.V('Cerca'), { after: 900 });
  await p.locator('input:visible').first().fill('Rossi'); await d.wait(1200);
  await d.shot({ t: 'Trovato in *un attimo*', s: 'Digiti “Rossi” e compare subito la prenotazione' });
};
ep.pre = async () => { for (const d of (await col('bookings').get()).docs) { const x = d.data(); if (x.name === 'Luca Moretti') await d.ref.update({ arrived: false, arrivedAt: null }); if (x.name === 'Elena Ferrari') await d.ref.update({ noShow: false }); if (x.name === 'Giulia Verdi') await d.ref.update({ people: 6 }); } };
director('serata', ep);
