const { director } = require('./director');
const ep = async d => {
  const { p } = d; const Q = sel => p.locator(sel).locator('visible=true').first();
  await p.evaluate(() => switchTab('impostazioni')); await d.wait(1000);
  const st = d.V('Staff'); await st.evaluate(e => e.scrollIntoView({ block: 'center' })); await d.wait(500);
  await d.shot({ b: 6, t: 'Chi lavora *con te*', s: 'Impostazioni › Staff' });
  await d.tap(st, { after: 1300 });
  await p.locator('input[type=email]:visible, input[placeholder="nome@esempio.it"]:visible').first().fill('cameriere@esempio.it');
  await d.shot({ b: 10, t: 'Inviti *per email*', s: 'Sala: solo prenotazioni e servizio. Gestione: accesso completo, anche piantina e impostazioni' });
  const add = Q('[onclick="openAddProfileModal()"]'); await add.evaluate(e => e.scrollIntoView({ block: 'center' })); await d.wait(500);
  await d.shot({ b: 8, t: 'Un tablet, *tanti camerieri*', s: 'I profili: niente account per ognuno, basta un nome' });
  await d.tap(add, { after: 1000 });
  await p.locator('#profile-form-name').fill('Marta'); await p.locator('#profile-form-pin').fill('1234'); await d.wait(300);
  await d.shot({ b: 8, t: 'Nome, ruolo e *PIN*', s: 'Il PIN è facoltativo: serve se non vuoi che altri usino il tuo profilo' });
  await d.tap(p.locator('#add-profile-modal button[type=submit], [id*=profile] button[type=submit]').locator('visible=true').first(), { after: 1300 });
  await p.evaluate(() => openAddProfileModal()); await d.wait(700); await p.locator('#profile-form-name').fill('Giorgio'); await p.locator('[id*=profile] button[type=submit]').locator('visible=true').first().click(); await d.wait(1200);
  await p.evaluate(() => openAddProfileModal()); await d.wait(700); await p.locator('#profile-form-name').fill('Sofia'); await p.locator('#profile-form-pin').fill('5678'); await p.locator('[id*=profile] button[type=submit]').locator('visible=true').first().click(); await d.wait(1200);
  await Q('#profiles-management-list').evaluate(e => e.scrollIntoView({ block: 'center' })); await d.wait(500);
  await d.shot({ b: 8, t: 'La *squadra*', s: 'Marta, Giorgio, Sofia: ognuno col suo profilo' });
  await p.evaluate(() => switchTab('impostazioni')); await d.wait(900);
  const pin = Q('#settings-require-pin-toggle'); await pin.evaluate(e => e.scrollIntoView({ block: 'center' })); await d.wait(500);
  await d.tap(pin, { after: 900 });
  await d.shot({ b: 6, t: 'PIN *obbligatorio*', s: 'Se lo attivi, cambiare profilo chiede il PIN' });
  await d.tap(p.locator('[aria-label="Apri menu"]'), { silent: true, after: 800 });
  await d.shot({ b: 6, t: 'Cambio *turno*', s: 'Dal menu, “Cambia profilo”' });
  await d.tap(d.R(/^\s*Cambia profilo/), { after: 1200 });
  await d.shot({ b: 8, t: 'Chi sei?', s: 'Ognuno tocca il suo nome' });
  await d.tap(p.locator('#profile-picker-cards').getByText('Marta').first(), { after: 1000 });
  await d.shot({ b: 6, t: 'PIN di *Marta*', s: 'Quattro cifre e sei dentro' });
  for (const c of '123') await p.locator(`[onclick="pinPadPress('${c}', this)"]`).locator('visible=true').first().click();
  await d.tap(p.locator(`[onclick="pinPadPress('4', this)"]`).locator('visible=true').first(), { after: 1500 });
  await p.evaluate(() => { const o = document.getElementById('profile-picker-overlay'); if (o && !o.classList.contains('hidden')) closeProfilePicker(); switchTab('tavoli'); }); await d.wait(900);
  await p.evaluate(() => openAppMenu()); await d.wait(800);
  await d.shot({ b: 6, t: 'Ora è *Marta*', s: 'Tutto quello che fa porta il suo nome', settle: 300 });
  await p.evaluate(() => closeAppMenu()); await d.wait(600);
  const card = p.locator('.swipe-fg:visible', { hasText: 'Paolo Ricci' }).first(); await card.evaluate(e => e.scrollIntoView({ block: 'center' })); await d.wait(500);
  await d.swipe(card, 230, { silent: true });
  await p.evaluate(() => switchTab('cronologia')); await d.wait(1600);
  await d.shot({ b: 10, t: 'Chi ha fatto *cosa*', s: 'La cronologia: ogni arrivo, prenotazione e modifica, con nome e ora' });
};
ep.pre = async () => { await db.collection('restaurants').doc(currentRestaurantId).update({ requireProfilePin: false }); try { localStorage.clear(); sessionStorage.clear(); } catch (e) {} if (typeof closeProfilePicker === 'function') closeProfilePicker(); for (const d of (await col('profiles').get()).docs) await d.ref.delete(); for (const d of (await col('bookings').get()).docs) if (d.data().name === 'Paolo Ricci') await d.ref.update({ arrived: false, arrivedAt: null }); };
director('staff', ep);
